2024-06-16 08:18 - updates

diff --git a/.github/actions/image_meta/action.yml b/.github/actions/image_meta/action.yml
--- a/.github/actions/image_meta/action.yml
+++ b/.github/actions/image_meta/action.yml
@@ -58,6 +58,11 @@ runs:
       shell: bash
       run: |
         ref=${{ inputs.image }}
+        if [[ -z $ref ]];
+          echo "::error:: No valid image provided"
+          exit 1
+        fi
+        
         architecture=${{ inputs.architecture }}
         echo "::notice:: Fetching meta for '${ref}' ${architecture}"
         repo="${ref%:*}"
